server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/dhanamjaya123/config-repository.git
          searchPaths: configuration-files-list
          username: xxxxxx
          password: xxxxxx 
profiles: default
      
       
