server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/dhanamjaya123/config-repository.git
          searchPaths: configuration-files-list
          username: xxxxx
          password: xxxxx
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
      
       
